# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MfaAuth < Formula
  desc "Helper tool to store and run "
  homepage ""
  version "0.0.4"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.4/mfa-auth_0.0.4_darwin_amd64.tar.gz"
      sha256 "d23e221e93218f9704639fb431074f0830f0a1206eb39136a79ca8182712757c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.4/mfa-auth_0.0.4_linux_amd64.tar.gz"
      sha256 "7682deeae36d23900d78c0fce17593bccb49446660f9207661e642625af11982"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.4/mfa-auth_0.0.4_linux_arm64.tar.gz"
      sha256 "a728e5ba9256712651b7041c2308f5bed339f78381eda157a24d87e83414518a"
    end
  end

  def install
    bin.install "program"
  end

  def caveats; <<~EOS
    Just use the inbuilt help
  EOS
  end
end
