# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MfaAuth < Formula
  desc "Helper tool to store and run "
  homepage ""
  version "0.0.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_darwin_amd64.tar.gz"
      sha256 "71f8869061a633091dbeb3adfea81be0dbc2522cef910dd3bfef52dd0d622c8a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_linux_amd64.tar.gz"
      sha256 "fba7e59820debfc7262d52ea08b7f2d476ae252329d3cc9c3400c4589e62fc96"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_linux_arm64.tar.gz"
      sha256 "164d84bc7599f372e57a1fea0ce3e858322145e8b2fee6ffb0e8bd578fe01d7e"
    end
  end

  def install
    bin.install "program"
  end

  def caveats; <<~EOS
    Just use the inbuilt help
  EOS
  end
end
