# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MfaAuth < Formula
  desc "Helper tool to store and run "
  homepage ""
  version "0.0.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_darwin_amd64.tar.gz"
      sha256 "48cf7bb877468382742100b2f649e590e5baea654b66fcef4bcde45392545ce1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_linux_amd64.tar.gz"
      sha256 "f23fbfad843e69d9e1ed79782e1f30c8f83b18b680fb6b4310817b34cdf3ced5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_linux_arm64.tar.gz"
      sha256 "0b4cffcbeec8888d75948d59bfc539d7a8ad846b6ff64ec8ad4329f1d642d151"
    end
  end

  def install
    bin.install "program"
  end

  def caveats; <<~EOS
    Just use the inbuilt help
  EOS
  end
end
