name: Go

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
    - 'test*'
  pull_request:
    branches:
    - 'master'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.6

    - name: Build
      run: go build -v ./...

    - name: check
      run: ls -aslh

    - name: check
      run: echo ${{github.event_name}}

    - name: check
      run: echo ${{github.ref}}

    - name: Test
      run: go test -v ./...

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: mfa-auth
        path: ./mfa-auth


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master'}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: check
      if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master'}}
      run: ./cross-build-upload.sh ${{ github.token }} ${{ github.ref }}